name: Build Submodules
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.CI_TOKEN }}
          submodules: true
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Build API submodule with Gradle
        run: ./gradlew submodule-api:build
      - name: Build Client submodule with Gradle
        run: ./gradlew submodule-client:build
      - name: Build Server submodule with Gradle
        run: ./gradlew submodule-server:build
      - name: Check files
        shell: bash
        run: ls
